[package]
name = "axum-keycloak-auth"
version = "0.5.0"
edition = "2021"
rust-version = "1.74.1"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/axum-keycloak-auth"
description = """
Protect axum routes with a JWT emitted by Keycloak.
"""
categories = ["authentication", "web-programming"]
keywords = ["keycloak", "auth", "jwt", "oidc", "axum"]

[dependencies]
axum = "0.7"
educe = { version = "0.5", default-features = false, features = ["Debug"] }
futures = "0.3"
http = "1"
jsonwebtoken = "9"
reqwest = { version = "0.11", features = ["json", "serde_json"], default-features = false }
serde = "1"
serde_json = "1"
serde_with = "3"
snafu = "0.8"
time = "0.3"
tokio = "1"
tower = "0.4"
tracing = "0.1"
try-again = "0.1"
typed-builder = "0.18"
url = "2"
uuid = { version = "1", features = ["v7"] }

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
rustls = ["reqwest/rustls", "reqwest/rustls-tls"]
